name: CI

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Dependencies
        run: brew install cc65 # gnu-tar
      - name: Build
        run: |
          npm install
          npm run pkg
          npm run package-mac
      - name: Test
        run: |
          arch -x86_64 ./dist/create-nes-game-macos-x64 \
            --unattended \
            --skip-version-check \
            --answer name=testgame \
            --answer use-tutorial=no \
            --answer mapper=nrom \
            --answer chr-ram=no \
            --answer prg-banks=1 \
            --answer chr-banks=1 \
            --answer mirroring=horizontal \
            --answer include-c=no \
            --answer ci-provider=none \
            --answer test-provider=nes-test \
            --answer emulator=mesen
